http://localhost:8181/user


###

POST http://localhost:8181/users HTTP/1.1
content-type: application/json

{    
    "name": "Norberto",
    "email": "Norberto@gmail.com"
}

###
http://localhost:8181/user/4
