version: '3.5'
services:

# Database Service (Oracle)
  db:
    image: enomoto/oracle-xe-11g-r2
    container_name: database
    ports:
      - 1521:1521
    #volumes:
    #  - db-data:/u01/app/oracle
    networks:
      - localhost
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - WEB_CONSOLE=false
      - ORACLE_SID=xe

# springboot
  springboot:
    image: enomoto/springdatajpa:oracle
    ports:
      - "8181:8181"
    restart: always
    depends_on: 
      - db # This service depends on db. Start that first.   
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - localhost
    container_name: springdatajpa-oracle

volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  localhost:

